const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const reportsDir = path.join(__dirname, "../uploads/reports");

if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
}

const generateReportPDF = ({
    reportName,
    reportType,
    startDate,
    endDate,
    departmentName,
    generatedByEmail,
    summary
}) => {
    return new Promise((resolve, reject) => {
        try {
            const fileName = `report-${Date.now()}.pdf`;
            const filePath = path.join(reportsDir, fileName);

            const doc = new PDFDocument({ margin: 50 });
            const stream = fs.createWriteStream(filePath);

            doc.pipe(stream);

            // Header
            doc.fontSize(20).text(reportName, { align: "center" });
            doc.moveDown();

            doc.fontSize(11);
            doc.text(`Report Type: ${reportType}`);
            doc.text(`Date Range: ${new Date(startDate).toDateString()} - ${new Date(endDate).toDateString()}`);
            doc.text(`Department: ${departmentName || "All Departments"}`);
            doc.text(`Generated By: ${generatedByEmail}`);
            doc.text(`Generated On: ${new Date().toLocaleString()}`);

            doc.moveDown();
            doc.fontSize(14).text("Summary", { underline: true });
            doc.moveDown(0.5);

            doc.fontSize(11);

            Object.entries(summary).forEach(([key, value]) => {
                // Convert camelCase key into a readable label
                const label = key
                    .replace(/([A-Z])/g, " $1")
                    .replace(/^./, (str) => str.toUpperCase());

                doc.text(`${label}: ${value}`);
            });

            doc.end();

            stream.on("finish", () => {
                const relativePath = path
                    .join("uploads/reports", fileName)
                    .replace(/\\/g, "/");

                resolve(relativePath);
            });

            stream.on("error", (err) => reject(err));

        } catch (error) {
            reject(error);
        }
    });
};

module.exports = generateReportPDF;